### ISSUE TITLE
✨[Feat] <이미지 추가 시 URL 설정 문제>

### ISSUE THREAD

**Issue by Jun-Young-Seo** [Engineering-Competition/PND-Front#10]
## 💡 About
README에 프로젝트(레포) 진행 중 사진을 올려야 할 일이 자주 있습니다.
Image 파일을 Base64 인코딩 할 시 URL이 너무 길어져 에디터 가독성이 크게 떨어집니다.
Github에 README 이미지 파일 업로드 시에는 Github에서 이미지 파일을 올릴 수 있는 서버를 제공해 줘서 짧게 쓸 수 있다고 합니다.

생각한 방법은 크게 두 가지 입니다.
1. REAMD.md 파일은 Github에서만 쓴다고 생각하고 GIsts(Github image server?) API를 활용해보기.
   - 이 경우가 더 나을 거 같긴 한데 Github API 공부가 필요해요
   
2. 우리가 만들 서버 또는 DB(배포 이후에만 가능. URL로 접근이라 공인IP필요)에 이미지를 업로드하는 경우. 
   - 로컬 환경에서 테스트는 가능합니다. 로컬 서버 돌리는 PC에 img 저장하고 API로 받아오는 식?
   - 배포 시점을 생각해보면 이것도 좀 애매... 에러가 날 가능성도 높아 보이고, 서버 DB에 올리자니 용량이 너무 클 듯 합니다. 

혹시 다른 좋은 아이디어 있으신 분은 부탁드립니다! 👍 👍

**Comment by Jun-Young-Seo** [comment]
![image](https://github.com/user-attachments/assets/1134d52a-64b7-45c2-af45-5f14f6cc4e0b)

사진 처럼 공개된 이미지(URL 유효, CORS 설정 되어있는 경우)는 렌더링이 가능한데, 두 번쨰 Private한 이미지는 사용이 불가능합니다. 렌더링 자체가 안돼요. 두 번째 이미지는 저희 P-nd 팀 Front 레포지토리 README 파일의 사진 링크입니다. Private Repo라서 렌더링이 안되는 것 같아요.

나중에 서버에 이미지를 저장하고, URL로 받아오는 방식을 API 호출해서 사용하게 될 것 같은데, 그 때 참고하려고 올려둡니다.

**Comment by khyaejin** [comment]
@Jun-Young-Seo @Hjwoon 

우선 이전에 백엔드 측에서는 S3 배포를 통해 사진을 관리하자는 의견이 나왔었습니다.
S3 서버에 사진을 배포하고 그 url을 배포된 저희 DB에 String 값으로 저장해 두는 거죠.

이 방법을 선택했을 경우 리드미에서 이미지를 올리는 로직을 정리해보자면

1) 프론트에서 User가 이미지를 선택해 업로드 할 수 있게 해준 후
<img width="220" alt="image" src="https://github.com/user-attachments/assets/e69dcbb1-d58b-4a0e-b172-1ae49fb4f4bf">

2) 업로드된 이미지파일을 폼데이터로 담아 API를 호출해주시는 겁니다. (아래 화면 '생성하기'에서 호출)
<img width="521" alt="image" src="https://github.com/user-attachments/assets/8d37a1a4-3532-4f95-a569-7a09ba63f6f1">

3) 그럼 백엔드가 그 API 로직에서 해당 이미지파일을 S3에 배포하고, 배포 후 URL을 String값으로 DB에 저장해두고, 그 URL을 API의 response값으로 넘겨주는 거죠.

원래 이렇게 진행하려고 했는데 방금 확인해보니 하나 문제점이 있긴 합니다.

S3로 배포를 하게 되면 (이전 프로젝트의 s3배포 예시를 하나 들고 왔습니다. 두분 모두 댓글 확인하시면 해당 링크는 삭제할 예정입니다.)
https://s3.ap-northeast-2.amazonaws.com/scapture-image/Stadium/%EC%8A%A4%ED%8A%B8%EB%A6%AC%ED%8A%B8%ED%92%8B%EC%82%B4%ED%8C%8C%ED%81%AC/%EC%8A%A4%ED%8A%B8%EB%A6%AC%ED%8A%B8%ED%92%8B%EC%82%B4%ED%8C%8C%ED%81%AC1
이런식으로 url이 나오게 됩니다. 

문제는 마크다운 문법에서 인식을 해 사진을 보여주지는 못하는 것 같습니다.

해당 링크를 타고 들어가는 경우에만
<img width="1141" alt="image" src="https://github.com/user-attachments/assets/9dae6b35-5ad4-40a6-a1c6-d9f8ac755e51">
이렇게 이미지가 보입니다.

우선 올리신 1,2 방법 모두 공부해보겠습니다. 
아마 2 방법이 더 쉬울 것 같긴 한데 1보다는 금액이 더 많이 들 것 같긴 하네요.
그리고 DB 배포(rds 사용) 필요하시다면 지금 바로 할 수 있습니다. 과금때문에 개발 후에 배포하려고 했던 거거든요:)

우선 여러 방법에 대해서 알아보고 있겠습니다!

**Comment by Jun-Young-Seo** [comment]
@khyaejin

혜진님 너무 상세하고 좋은 답변 감사합니다 :)

![image](https://github.com/user-attachments/assets/88bf3604-bd5c-4ac3-bade-1f363b41089b)

혜진님이 올려주신 URL도 리드미 에디터에서 이미지로 잘 변환 됩니당. 그냥 복사하면 **한글**로 url이 바뀌어서, 다시 인코딩했어요. 추후에 URL 리턴하는 API 만드실 때 참고하시면 좋을 것 같습니다.

URL 테스트를 어디서 하신지는 모르겠지만 마크다운 프로그램(Typora)이나 github의 마크다운 변환기 모두 엔진이 달라서 그럴 수 있다고 하네요. 


저도 2번 방식이 더 좋다고 생각해요. 1번은 되는지도 애매한데다, 관련해서 검색해도 정보가 잘 없더라구요. 그냥 깃헙 자기 레포지토리(PUBLIC이어야 합니다)에 사진을 직접 올려서 생성되는 URL은 에디터에서 이미지로 잘 변환되는 것을 확인했습니다! 굳이 이미지를 서버에 저장하지 않고, 사용자가 자기 레포에 업로드하게 유도? 하는 방식도 사용할 수는 있을 것 같아요. 리드미를 만들어주기 위해 리드미를 먼저 만들라는게 좀 이상하긴 하지만...😅


당장 배포가 필요한 것은 아닙니다! 과금 문제도 있고, 아직 해야할 일들이 많이 있으니까요!
추가적으로 알게 되거나 필요한 사실 있으면 또 말씀드리겠습니다 :) 
이슈는 지운님 예빈님 보실 때 까지 열어두겠습니다
